### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [sibananda0718/Blockchain-Based-Security-Management-System-#1]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by Ishitagu** [comment]
hi! i would like to contribute to this issue , please assign it to me.

**Comment by KiranBaliga** [comment]
I am a newbie contributor and I have an experience of merged PR's on setting up documentation and licensing works on project Repos. I understand this is a FIFO request. As a supportive contributor, please assign the task to the first requestor. But in case, if it all, there is a scope of chance post the first requestor's commits, I would be happy to contribute :-) Thank you for viewing!

**Comment by sibananda0718** [comment]
I have updated the code of conduct .
